Thisis file contents is a notificaiton that the USS API swagger.yaml on github had 
a bug. Due to an error setting up swaggerhub to github integrations, its file contents 
were actually the FIMS API.  

This notification is on the release branch only. 

The USS APIs did not change between v17.11 and v17.10, but the models did.
Please refer to the domain spec for the model definitions for v17.10 at
https://github.com/nasa/utm-apis/tree/tcl3_v17.11/utm-domains
